### ISSUE TITLE
支持组织的logo 文件需上传

### ISSUE THREAD

**Issue by lijiangsheng1** [ospocommunity/website#4]
[LFAPAC_Logo_NEW.zip](https://github.com/ospocommunity/website/files/14489333/LFAPAC_Logo_NEW.zip)
[Evangelist.Front.Logo.zip](https://github.com/ospocommunity/website/files/14489334/Evangelist.Front.Logo.zip)
[LFOSSA.logo.zip](https://github.com/ospocommunity/website/files/14489335/LFOSSA.logo.zip)
![天工开物](https://github.com/ospocommunity/website/assets/1545933/4d432732-8b22-4a9a-b84d-127dfdc7da85)

**Comment by robinv8** [comment]
已更新
https://ospo.events/support.html
![image](https://github.com/ospocommunity/website/assets/12277531/6f99e139-4b26-4a72-8e49-4e6bdbbb81d1)
